#!/bin/bash
#
# pyap     Run daemon to notify supervision status.
#
# Authors:      fccagou <fccagou@gmail.com>
#
# chkconfig: 12345 99 10
# description: Lights on led depending url status.
#
### BEGIN INIT INFO
# Default-Start: 12345
# Default-Stop:  0 6
# Required-Start: $local_fs
# Required-Stop:
# Short-Description: Lights on led depending url status.
# Description: Lights on led depending url status.
# Provides: pyap
### END INIT INFO

. /etc/rc.d/init.d/functions

URL=
PRG=/usr/bin/pyap
PYAP_OPTS=""

[ -f /etc/sysconfig/pyap ] && . /etc/sysconfig/pyap

[ -n "${TTY}" ] && PYAP_OPTS="${PYAP_OPTS} --tty ${TTY}"

# See how we were called.
case "$1" in
  start)
	PID="$(ps aux | grep ${PRG} | grep -v grep  | awk '{ print $2 }')"
	if [ -n "${PID}" ]
	then
		success "pyap is running"
		echo
		exit 0
	fi

	${PRG} ${PYAP_OPTS} ${URL} 2>&1 > /var/log/pyap.log &
	sleep 1
	PID="$(ps aux | grep ${PRG} | grep -v grep  | awk '{ print $2 }')"
	if [ -n "${PID}" ]
	then
		success "pyap started"
		echo
	else
		failure "pyap started"
		echo
		exit 1
	fi
	exit 0

	;;
  stop)

	kill $(ps aux | grep ${PRG} | grep -v grep  | awk '{ print $2 }')
	success "pyap stopped"
	exit 0

	;;
  status)
	PID="$(ps aux | grep ${PRG} | grep -v grep  | awk '{ print $2 }')"
	if [ -z "${PID}" ]
	then
		echo "pyap not running"
	else
		echo "pyap running with pid ${PID}"
	fi
	exit 0
	;;
  *)
        echo $"Usage: $0 {start|stop|status}"
        exit 2
esac
exit 0
